package com.iunetworks.transferservice.model;


public enum AmountTransferType {

  PHYSICAL_ACCOUNT_TO_PHYSICAL_ACCOUNT,
  PHYSICAL_ACCOUNT_TO_LEGAL_ACCOUNT,
  PHYSICAL_ACCOUNT_TO_LEGAL_CARD,
  PHYSICAL_ACCOUNT_TO_PHYSICAL_CARD,

  PHYSICAL_CARD_TO_PHYSICAL_CARD,
  PHYSICAL_CARD_TO_LEGAL_ACCOUNT,
  PHYSICAL_CARD_TO_LEGAL_CARD,
  PHYSICAL_CARD_TO_PHYSICAL_ACCOUNT,

  LEGAL_ACCOUNT_TO_LEGAL_ACCOUNT,
  LEGAL_ACCOUNT_TO_PHYSICAL_ACCOUNT,
  LEGAL_ACCOUNT_TO_PHYSICAL_CARD,
  LEGAL_ACCOUNT_TO_LEGAL_CARD,

  LEGAL_CARD_TO_LEGAL_CARD,
  LEGAL_CARD_TO_LEGAL_ACCOUNT,
  LEGAL_CARD_TO_PHYSICAL_CARD,
  LEGAL_CARD_TO_PHYSICAL_ACCOUNT,


}


